config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require "sidekiq/web"
require "sidekiq/cron/web"
Sidekiq::Web.set :sessions, false # disable rack session cookie

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :report, except: %i(edit new show)

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  # Federation
  mount DiasporaFederation::Engine => "/"

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares, only: %i(create)

  resources :status_messages, :only => [:new, :create]

  resources :posts, only: %i(show destroy) do
    member do
      get :mentionable
    end

    resource :participation, only: %i(create destroy)
    resources :poll_participations, only: :create
    resources :likes, only: %i(create destroy index)
    resources :comments, only: %i(new create destroy index)
    resources :reshares, only: :index
  end

  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
  get "activity" => "streams#activity", :as => "activity_stream"
  get "stream" => "streams#multi", :as => "stream"
  get "public" => "streams#public", :as => "public_stream"
  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
  get "liked" => "streams#liked", :as => "liked_stream"
  get "commented" => "streams#commented", :as => "commented_stream"
  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects, except: %i(index new edit) do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, only: %i(destroy create) do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations, except: %i(edit update destroy)  do
    resources :messages, only: %i(create)
    delete 'visibility' => 'conversation_visibilities#destroy'
    get "raw"
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end


  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  # Users and people

  resource :user, only: %i(edit destroy), shallow: true do
    put :edit, action: :update
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
    post :auth_token
  end

  controller :users do
    get "public/:username"          => :public,                  :as => :users_public
    get "getting_started"           => :getting_started,         :as => :getting_started
    get "confirm_email/:token"      => :confirm_email,           :as => :confirm_email
    get "privacy"                   => :privacy_settings,        :as => :privacy_settings
    put "privacy"                   => :update_privacy_settings, :as => :update_privacy_settings
    get "getting_started_completed" => :getting_started_completed
  end

  devise_for :users, controllers: {sessions: :sessions}, skip: :registration
  devise_scope :user do
    get "/users/sign_up" => "registrations#new",    :as => :new_user_registration
    post "/users"        => "registrations#create", :as => :user_registration
  end

  get "users/invitations"  => "invitations#new",    :as => "new_user_invitation"
  post "users/invitations" => "invitations#create", :as => "user_invitation"

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope "admins", controller: :admins do
    match :user_search, via: [:get, :post]
    get :admin_inviter
    get :weekly_user_stats
    get :stats, as: "pod_stats"
    get :dashboard, as: "admin_dashboard"
    get "add_invites/:invite_code_id" => "admins#add_invites", :as => "add_invites"
  end

  namespace :admin do
    resources :pods, only: :index do
      post :recheck
    end

    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts, only: %i(index)
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, only: %i(show index) do
    resources :status_messages, only: %i(new create)
    resources :photos, except:  %i(new update)
    get :contacts
    get :stream
    get :hovercard

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }

  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'
  get "/m", to: "home#force_mobile", as: "force_mobile"

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  # NodeInfo
  get ".well-known/nodeinfo", to: "node_info#jrd"
  get "nodeinfo/:version",    to: "node_info#document", as: "node_info", constraints: {version: /\d+\.\d+/}
  get "statistics",           to: "node_info#statistics"

  # Terms
  if AppConfig.settings.terms.enable? || Rails.env.test?
    get 'terms' => 'terms#index'
  end

  # Relay
  get ".well-known/x-social-relay" => "social_relay#well_known"

  # Startpage
  root :to => 'home#show'
  get "podmin", to: "home#podmin"

  namespace :api do
    namespace :openid_connect do
      resources :clients, only: :create
      get "clients/find", to: "clients#find"

      post "access_tokens", to: "token_endpoint#create"

      # Authorization Servers MUST support the use of the HTTP GET and POST methods at the Authorization Endpoint
      # See http://openid.net/specs/openid-connect-core-1_0.html#AuthResponseValidation
      resources :authorizations, only: %i(new create destroy)
      post "authorizations/new", to: "authorizations#new"
      get "user_applications", to: "user_applications#index"
      get "jwks.json", to: "id_tokens#jwks"
      match "user_info", to: "user_info#show", via: %i(get post)
    end
  end

  get ".well-known/openid-configuration", to: "api/openid_connect/discovery#configuration"
end

app/models/pod.rb
class Pod < ApplicationRecord
  enum status: %i(
    unchecked
    no_errors
    dns_failed
    net_failed
    ssl_failed
    http_failed
    version_failed
    unknown_error
  )

  ERROR_MAP = {
    ConnectionTester::AddressFailure  => :dns_failed,
    ConnectionTester::DNSFailure      => :dns_failed,
    ConnectionTester::NetFailure      => :net_failed,
    ConnectionTester::SSLFailure      => :ssl_failed,
    ConnectionTester::HTTPFailure     => :http_failed,
    ConnectionTester::NodeInfoFailure => :version_failed
  }

  # this are only the most common errors, the rest will be +unknown_error+
  CURL_ERROR_MAP = {
    couldnt_resolve_host:         :dns_failed,
    couldnt_connect:              :net_failed,
    operation_timedout:           :net_failed,
    ssl_cipher:                   :ssl_failed,
    ssl_cacert:                   :ssl_failed,
    redirected_to_other_hostname: :http_failed
  }.freeze

  DEFAULT_PORTS = [URI::HTTP::DEFAULT_PORT, URI::HTTPS::DEFAULT_PORT]

  has_many :people

  scope :check_failed, lambda {
    where(arel_table[:status].gt(Pod.statuses[:no_errors])).where.not(status: Pod.statuses[:version_failed])
  }

  validate :not_own_pod

  class << self
    def find_or_create_by(opts) # Rename this method to not override an AR method
      uri = URI.parse(opts.fetch(:url))
      port = DEFAULT_PORTS.include?(uri.port) ? nil : uri.port
      find_or_initialize_by(host: uri.host, port: port).tap do |pod|
        pod.ssl ||= (uri.scheme == "https")
        pod.save
      end
    end

    # don't consider a failed version reading to be fatal
    def offline_statuses
      [Pod.statuses[:dns_failed],
       Pod.statuses[:net_failed],
       Pod.statuses[:ssl_failed],
       Pod.statuses[:http_failed],
       Pod.statuses[:unknown_error]]
    end

    def check_all!
      Pod.find_in_batches(batch_size: 20) {|batch| batch.each(&:test_connection!) }
    end

    def check_scheduled!
      Pod.where(scheduled_check: true).find_each(&:test_connection!)
    end
  end

  def offline?
    Pod.offline_statuses.include?(Pod.statuses[status])
  end

  # a pod is active if it is online or was online less than 14 days ago
  def active?
    !offline? || offline_since.try {|date| date > DateTime.now.utc - 14.days }
  end

  def to_s
    "#{id}:#{host}"
  end

  def schedule_check_if_needed
    update_column(:scheduled_check, true) if offline? && !scheduled_check
  end

  def test_connection!
    result = ConnectionTester.check uri.to_s
    logger.debug "tested pod: '#{uri}' - #{result.inspect}"

    transaction do
      update_from_result(result)
    end
  end

  # @param path [String]
  # @return [String]
  def url_to(path)
    uri.tap {|uri| uri.path = path }.to_s
  end

  def update_offline_since
    if offline?
      self.offline_since ||= DateTime.now.utc
    else
      self.offline_since = nil
    end
  end

  private

  def update_from_result(result)
    self.status = status_from_result(result)
    update_offline_since
    logger.warn "OFFLINE #{result.failure_message}" if offline?

    attributes_from_result(result)
    touch(:checked_at)
    self.scheduled_check = false

    save
  end

  def attributes_from_result(result)
    self.ssl ||= result.ssl
    self.error = result.failure_message[0..254] if result.error?
    self.software = result.software_version[0..254] if result.software_version.present?
    self.response_time = result.rt
  end

  def status_from_result(result)
    if result.error?
      ERROR_MAP.fetch(result.error.class, :unknown_error)
    else
      :no_errors
    end
  end

  # @return [URI]
  def uri
    @uri ||= (ssl ? URI::HTTPS : URI::HTTP).build(host: host, port: port)
    @uri.dup
  end

  def not_own_pod
    pod_uri = AppConfig.pod_uri
    pod_port = DEFAULT_PORTS.include?(pod_uri.port) ? nil : pod_uri.port
    errors.add(:base, "own pod not allowed") if pod_uri.host == host && pod_port == port
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  respond_to :html, :mobile, :json, :js

  def index
    @visibilities = ConversationVisibility.includes(:conversation)
                                          .order("conversations.updated_at DESC")
                                          .where(person_id: current_user.person_id)
                                          .paginate(page: params[:page], per_page: 15)

    if params[:conversation_id]
      @conversation = Conversation.joins(:conversation_visibilities)
                                  .where(conversation_visibilities: {
                                           person_id:       current_user.person_id,
                                           conversation_id: params[:conversation_id]
                                         }).first

      if @conversation
        @first_unread_message_id = @conversation.first_unread_message(current_user).try(:id)
        @conversation.set_read(current_user)
      end
    end

    gon.contacts = contacts_data

    respond_with do |format|
      format.html { render "index", locals: {no_contacts: current_user.contacts.mutual.empty?} }
      format.json { render json: @visibilities.map(&:conversation), status: 200 }
    end
  end

  def create
    # Contacts autocomplete does not work the same way on mobile and desktop
    # Mobile returns contact ids array while desktop returns person id
    # This will have to be removed when mobile autocomplete is ported to Typeahead
    recipients_param, column = [%i(contact_ids id), %i(person_ids person_id)].find {|param, _| params[param].present? }
    if recipients_param
      person_ids = current_user.contacts.mutual.where(column => params[recipients_param].split(",")).pluck(:person_id)
    end

    unless person_ids.present?
      render plain: I18n.t("javascripts.conversation.create.no_recipient"), status: 422
      return
    end

    opts = params.require(:conversation).permit(:subject)
    opts[:participant_ids] = person_ids
    opts[:message] = { text: params[:conversation][:text] }
    @conversation = current_user.build_conversation(opts)

    if @conversation.save
      Diaspora::Federation::Dispatcher.defer_dispatch(current_user, @conversation)
      flash[:notice] = I18n.t("conversations.create.sent")
      render json: {id: @conversation.id}
    else
      render plain: I18n.t("conversations.create.fail"), status: 422
    end
  end

  def show
    respond_to do |format|
      format.html do
        redirect_to conversations_path(conversation_id: params[:id])
        return
      end

      if @conversation = current_user.conversations.where(id: params[:id]).first
        @first_unread_message_id = @conversation.first_unread_message(current_user).try(:id)
        @conversation.set_read(current_user)

        format.json { render :json => @conversation, :status => 200 }
      else
        redirect_to conversations_path
      end
    end
  end

  def raw
    @conversation = current_user.conversations.where(id: params[:conversation_id]).first
    if @conversation
      @first_unread_message_id = @conversation.first_unread_message(current_user).try(:id)
      @conversation.set_read(current_user)
      render partial: "conversations/show", locals: {conversation: @conversation}
    else
      head :not_found
    end
  end

  def new
    if !params[:modal] && !session[:mobile_view] && request.format.html?
      redirect_to conversations_path
      return
    end

    if session[:mobile_view] == true && request.format.html?
      @contacts_json = contacts_data.to_json

      @contact_ids = if params[:contact_id]
                       current_user.contacts.find(params[:contact_id]).id
                     elsif params[:aspect_id]
                       current_user.aspects.find(params[:aspect_id]).contacts.pluck(:id).join(",")
                     end

      render :layout => true
    else
      if params[:contact_id]
        gon.push conversation_prefill: [current_user.contacts.find(params[:contact_id]).person.as_json]
      elsif params[:aspect_id]
        gon.push conversation_prefill: current_user.aspects
                                                   .find(params[:aspect_id]).contacts.map {|c| c.person.as_json }
      end
      render :layout => false
    end
  end

  private

  def contacts_data
    current_user.contacts.mutual.joins(person: :profile)
      .pluck(*%w(contacts.id profiles.first_name profiles.last_name people.diaspora_handle))
      .map {|contact_id, *name_attrs|
        {value: contact_id, name: ERB::Util.h(Person.name_from_attrs(*name_attrs)) }
      }
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def conversation_class(conversation, unread_count, selected_conversation_id)
    conv_class = unread_count > 0 ? "unread " : ""
    if selected_conversation_id && conversation.id == selected_conversation_id
      conv_class << "selected"
    end
    conv_class
  end
end

app/views/conversations/_conversation.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

- conversation = visibility.conversation
.conversation-wrapper{ :"data-conversation-path" => conversation_path(conversation) }
  .stream-element.conversation{data:  {guid: conversation.id},
                               class: conversation_class(conversation, visibility.unread, @conversation.try(:id))}
    .media
      .img
        - other_participants = conversation.ordered_participants - [current_user.person]
        - if other_participants.first.present?
          = person_image_tag(other_participants.first)
          - if other_participants.count > 1
            .participants_count
              = other_participants.count - 1

      .bg
        .badge.badge-default.message-count.pull-right
          = conversation.messages.size
        - if visibility.unread > 0
          .badge.badge-important.unread-message-count.pull-right
            = visibility.unread
        .subject
          %div{ :class => direction_for(conversation.subject) }
            = conversation.subject
        .timestamp
          = timeago(conversation.updated_at)
        .last_author
          - if conversation.last_author.present?
            = conversation.last_author.name
        .last_message
          - if conversation.messages.present?
            %em
              = conversation.messages.last.message.plain_text_without_markdown
        - if other_participants.count > 1
          .participants
            - other_participants.drop(1).take(15).each do |participant|
              = person_image_tag(participant)

app/views/conversations/_conversation.mobile.haml
- conversation = visibility.conversation
%a.conversation{ :href => conversation_path(conversation) }
  .stream-element.conversation{data: {guid: conversation.id}, class: ("unread" if visibility.unread > 0)}
    .media
      .img
        = person_image_tag(conversation.author, size: :thumb_small)

      .bg
        = render partial: "conversation_subject",
                 locals:  { conversation: conversation, unread_count: visibility.unread }

        .last_author
          .timestamp
            = timeago(conversation.updated_at)

          - if conversation.last_author.present?
            = conversation.last_author.name

          - if conversation.participants.size > 2
            %span.participant_count
              = "(+#{conversation.participants.size - 1})"

app/views/conversations/_conversation_subject.haml
.subject
  .badge.badge-default.message-count.pull-right
    = conversation.messages.size
  - if unread_count > 0
    .badge.badge-important.unread-message-count.pull-right
      = unread_count

  %div{ :class => direction_for(conversation.subject) }
    = conversation.subject[0..30]

app/views/conversations/_message.html.haml
.stream-element.message{data: {guid: message.id}, id: ("first_unread" if @first_unread_message_id == message.id)}
  .media
    = person_image_link(message.author, size: :thumb_small, class: "img")
    .bd
      = person_link(message.author, class: "author from")
      = timeago(message.created_at)

      %div{class: direction_for(message.text)}
        .message-content
          = message.message.markdownified

app/views/conversations/_message.mobile.haml
.stream-element.message{data: {guid: message.id}, id: ("first_unread" if @first_unread_message_id == message.id)}
  .media
    .media-left
      = person_image_link(message.author, size: :thumb_small, class: "media-object")
    .media-body
      = person_link(message.author, class: "author from")
      = timeago(message.created_at)

      %div{class: direction_for(message.text)}
        .message-content
          = message.message.markdownified

app/views/conversations/_messages.haml
.stream
  = render partial: "message", collection: conversation.messages

  .stream-element.new-message
    .media
      .media-left
        = owner_image_tag(:thumb_small)
      .media-body
        = form_for [conversation, Message.new], html: {id: "response-message", class: "control-group"} do |message|
          .form-group
            %label.sr-only#message-label{for: "response-message-text"}= t("conversations.new.message")
            = message.text_area :text,
                                rows: 5,
                                tabindex: 1,
                                id: "response-message-text",
                                class: "form-control form-group conversation-message-text",
                                aria: {labelledby: "message-label"}

          = message.submit t("conversations.show.reply"),
                                "data-disable-with" => t("conversations.show.replying"),
                                :class => "btn btn-primary pull-right",
                                :tabindex => 2
          .clearfix

app/views/conversations/_new.haml
.container-fluid
  = form_for Conversation.new, html: {id: "new-conversation",
    class: "new-conversation form-horizontal"}, remote: true do |conversation|
    .form-group
      %label#to-label{for: "contacts-search-input"}= t(".to")
      .recipients-tag-list.clearfix#recipients-tag-list
      = text_field_tag "contact_autocomplete",
                       nil,
                       id: "contacts-search-input",
                       class: "form-control",
                       autocomplete: "off"

      - unless defined?(mobile) && mobile
        = text_field_tag "person_ids", nil, id: "contact-ids", type: "hidden",
                                            aria: {labelledby: "to-label"}

    .form-group
      %label#subject-label{for: "conversation-subject"}
        = t(".subject")
      = conversation.text_field :subject,
                                id: "conversation-subject",
                                class: "input-block-level form-control",
                                aria:  {labelledby: "subject-label"},
                                value: "",
                                placeholder: t("conversations.new.subject_default")

    .form-group
      %label.sr-only#message-label{for: "new-message-text"}= t(".message")
      = text_area_tag "conversation[text]", "",
                                rows: 5,
                                id: "new-message-text",
                                class: "conversation-message-text input-block-level form-control",
                                aria: {labelledby: "message-label"}

    .form-group
      = conversation.submit t(".send"), "data-disable-with" => t(".sending"), :class => "btn btn-primary pull-right"

app/views/conversations/_show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.conversation-participants.framed-content.clearfix
  .control-icons.pull-right
    - if conversation.participants.count > 1
      = link_to content_tag(:i, nil, class: "entypo-cross"),
                conversation_visibility_path(conversation),
                method: "delete",
                data:   {confirm: "#{t('.hide')}?"},
                title:  t(".hide"),
                class:  "hide_conversation"
    - else
      = link_to content_tag(:i, nil, class: "entypo-trash"),
                conversation_visibility_path(conversation),
                method: "delete",
                data:   {confirm: "#{t('.delete')}?"},
                title:  t(".delete"),
                class:  "delete_conversation"

  %h3{ :class => direction_for(conversation.subject) }
    = conversation.subject

  - for participant in conversation.participants
    = person_image_link(participant, :size => :thumb_small)

= render partial: "messages", locals: {conversation: conversation}

app/views/conversations/_show.mobile.haml
-# Copyright (c) 2010-2011, Diaspora Inc. This file is
-# licensed under the Affero General Public License version 3 or later. See
-# the COPYRIGHT file.

.conversation
  .conversation-participants.header-full-width
    .delete_conversation.pull-right
      = link_to(raw("<i class='entypo-trash'></i>"), conversation_visibility_path(conversation),
              method: 'delete', data: { confirm: "#{t('.delete')}?" }, class: "remove")

    %h3
      = conversation.subject
    .last-message-timeago
      != t('.last_message', timeago: timeago(conversation.updated_at))

    .avatars
      - for participant in conversation.participants
        .avatar
          = person_image_link(participant, size: :thumb_small)
    .clear

  = render partial: 'messages', locals: { conversation: conversation }

app/views/conversations/index.haml
- content_for :page_title do
  = t(".conversations_inbox")

.container-fluid#conversations-container
  .row
    .col-md-4
      .sidebar#left_pane
        .sidebar-header.clearfix#left_pane_header
          .pull-right
            = link_to t(".new_conversation"), conversations_path, class: "new-conversation-btn btn btn-default"
          %h3
            = t(".inbox")

        .conversation-inbox#conversation-inbox
          .conversations-form-container.stream.conversations
            - if @visibilities.count > 0
              = render partial: "conversations/conversation", collection: @visibilities, as: :visibility
            - else
              .no-conversations
                = t(".no_messages")
            .pagination-container
              = will_paginate @visibilities, previous_label: "&laquo;", next_label: "&raquo;", inner_window: 1,
                  renderer: WillPaginate::ActionView::BootstrapLinkRenderer
    .col-md-8
      .conversations-form-container.stream_container
        #conversation-show{class: @conversation ? "" : "hidden"}
          - if @conversation
            = render 'conversations/show', conversation: @conversation
        #conversation-new{class: @conversation ? "framed-content clearfix hidden" : "framed-content clearfix"}
          .new-conversation
            %h3.text-center= t("conversations.index.new_conversation")
            - if no_contacts
              .well.text-center= t("javascripts.conversation.new.no_contacts")
            - else
              = render "conversations/new"

app/views/conversations/index.mobile.haml
-#   Copyright (c) 2010-2012, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.clearfix.conversations-title
  %h3= t(".inbox")
  = link_to t(".new_conversation"), new_conversation_path, class: "btn btn-default pull-right"

- flash.each do |name, msg|
  .alert{class: "alert-#{flash_class name}", role: "alert"}
    = msg

.conversation-inbox#conversation-inbox
  .stream.conversations
    - if @visibilities.count > 0
      = render partial: "conversations/conversation", collection: @visibilities, as: :visibility
    - else
      .no-messages
        %i
          = t(".no_messages")

  = will_paginate @visibilities, previous_label: "&laquo;", next_label: "&raquo;", inner_window: 1, outer_window: 0,
      renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/conversations/new.html.haml
= include_gon camel_case: true
= render 'conversations/new'

app/views/conversations/new.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

%script{nonce: content_security_policy_nonce(:script)}
  :plain
    $(document).ready(function () {
      var data = $.parseJSON( "#{escape_javascript(@contacts_json).html_safe}" ),
          autocompleteInput = $("#contacts-search-input");

      autocompleteInput.autoSuggest(data, {
        selectedItemProp: "name",
        searchObjProps: "name",
        asHtmlID: "contact_ids",
        retrieveLimit: 10,
        minChars: 1,
        keyDelay: 0,
        startText: "",
        emptyText: "#{t("no_results")}",
        preFill: [{name : "#{h params[:name]}",
                   value : "#{@contact_ids}"}]
        });
      autocompleteInput.focus();
    });

.col-md-6.col-md-offset-3#new_conversation_pane
  .container-fluid.row
    %h3
      = t("conversations.index.new_conversation")

  = render "conversations/new", mobile: true

app/views/conversations/show.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= render 'show', :conversation => @conversation